create table PinholeMetaData (
	id serial,
	instance integer null references Instance(id),
	shortname varchar(255),
	title varchar(255),
	show boolean default false,
	machine_tag boolean default false,
	displayorder integer not null default 0,
	primary key (id)
);

CREATE INDEX PinholeMetaData_shortname_index ON PinholeMetaData(shortname);
CREATE INDEX PinholeMetaData_instance_index ON PinholeMetaData(instance);

insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('exiftoolversion', 'ExifTool Version Number', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('filename', 'File Name', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('directory', 'Directory', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('filesize', 'File Size', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('filemodifydate', 'File Modification Date/Time', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('filetype', 'File Type', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('mimetype', 'MIME Type', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('make', 'Make', true, true, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('model', 'Camera Model Name', true, true, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('orientation', 'Orientation', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('xresolution', 'X Resolution', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('yresolution', 'Y Resolution', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('resolutionunit', 'Resolution Unit', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('modifydate', 'Modify Date', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('ycbcrpositioning', 'Y Cb Cr Positioning', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('exposuretime', 'Exposure Time', true, true, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('fnumber', 'F Number', true, true, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('exposureprogram', 'Exposure Program', true, true, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('iso', 'ISO', true, true, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('exifversion', 'Exif Version', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('datetimeoriginal', 'Date/Time Original', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('createdate', 'Create Date', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('componentsconfiguration', 'Components Configuration', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('shutterspeedvalue', 'Shutter Speed Value', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('aperturevalue', 'Aperture Value', true, true, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('flash', 'Flash', true, true, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('focallength', 'Focal Length', true, true, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('macromode', 'Macro Mode', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('self-timer', 'Self-timer', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('quality', 'Quality', true, true, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('canonflashmode', 'Canon Flash Mode', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('continuousdrive', 'Continuous Drive', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('focusmode', 'Focus Mode', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('recordmode', 'Record Mode', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('canonimagesize', 'Canon Image Size', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('easymode', 'Easy Mode', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('digitalzoom', 'Digital Zoom', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('contrast', 'Contrast', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('sharpness', 'Sharpness', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('meteringmode', 'Metering Mode', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('focusrange', 'Focus Range', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('canonexposuremode', 'Canon Exposure Mode', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('lenstype', 'Lens Type', true, true, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('longfocal', 'Long Focal', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('shortfocal', 'Short Focal', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('focalunits', 'Focal Units', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('flashactivity', 'Flash Activity', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('flashbits', 'Flash Bits', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('focuscontinuous', 'Focus Continuous', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('zoomsourcewidth', 'Zoom Source Width', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('zoomtargetwidth', 'Zoom Target Width', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('photoeffect', 'Photo Effect', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('focaltype', 'Focal Type', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('focalplanexsize', 'Focal Plane X Size', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('focalplaneysize', 'Focal Plane Y Size', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('autoiso', 'Auto ISO', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('baseiso', 'Base ISO', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('measuredev', 'Measured EV', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('targetaperture', 'Target Aperture', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('targetexposuretime', 'Target Exposure Time', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('exposurecompensation', 'Exposure Compensation', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('whitebalance', 'White Balance', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('slowshutter', 'Slow Shutter', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('sequencenumber', 'Shot Number In Continuous Burst', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('opticalzoomcode', 'Optical Zoom Code', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('flashguidenumber', 'Flash Guide Number', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('flashexposurecomp', 'Flash Exposure Compensation', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('autoexposurebracketing', 'Auto Exposure Bracketing', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('aebbracketvalue', 'AEB Bracket Value', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('focusdistanceupper', 'Focus Distance Upper', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('focusdistancelower', 'Focus Distance Lower', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('bulbduration', 'Bulb Duration', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('cameratype', 'Camera Type', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('autorotate', 'Auto Rotate', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('ndfilter', 'ND Filter', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('self-timer2', 'Self-timer 2', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('canonimagetype', 'Canon Image Type', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('canonfirmwareversion', 'Canon Firmware Version', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('ownername', 'Owner Name', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('serialnumber', 'Camera Body No.', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('setbuttoncrosskeysfunc', 'Set Button Cross Keys Func', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('longexposurenoisereduction', 'Long Exposure Noise Reduction', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('flashsyncspeedav', 'Flash Sync Speed Av', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('shutter-aelock', 'Shutter-AE Lock', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('afassistbeam', 'AF Assist Beam', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('exposurelevelincrements', 'Exposure Level Increments', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('mirrorlockup', 'Mirror Lockup', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('ettlii', 'E-TTL II', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('shuttercurtainsync', 'Shutter Curtain Sync', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('canonmodelid', 'Canon Model ID', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('numafpoints', 'Num AF Points', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('canonimagewidth', 'Canon Image Width', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('canonimageheight', 'Canon Image Height', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('canonimagewidthasshot', 'Canon Image Width As Shot', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('canonimageheightasshot', 'Canon Image Height As Shot', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('afpointsused', 'AF Points Used', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('serialnumberformat', 'Serial Number Format', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('originaldecisiondata', 'Original Decision Data', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('filenumber', 'File Number', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('bracketmode', 'Bracket Mode', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('bracketvalue', 'Bracket Value', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('bracketshotnumber', 'Bracket Shot Number', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('noisereduction', 'Noise Reduction', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('wbbracketmode', 'WB Bracket Mode', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('wbbracketvalueab', 'WB Bracket Value AB', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('wbbracketvaluegm', 'WB Bracket Value GM', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('filtereffect', 'Filter Effect', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('toningeffect', 'Toning Effect', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('tonecurve', 'Tone Curve', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('sharpnessfrequency', 'Sharpness Frequency', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('sensorredlevel', 'Sensor Red Level', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('sensorbluelevel', 'Sensor Blue Level', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('whitebalancered', 'White Balance Red', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('whitebalanceblue', 'White Balance Blue', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('colortemperature', 'Color Temperature', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('picturestyle', 'Picture Style', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('digitalgain', 'Digital Gain', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('wbshiftab', 'WB Shift AB', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('wbshiftgm', 'WB Shift GM', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('sensorwidth', 'Sensor Width', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('sensorheight', 'Sensor Height', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('sensorleftborder', 'Sensor Left Border', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('sensortopborder', 'Sensor Top Border', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('sensorrightborder', 'Sensor Right Border', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('sensorbottomborder', 'Sensor Bottom Border', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('wb_rggblevelsasshot', 'WB RGGB Levels As Shot', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('colortempasshot', 'Color Temp As Shot', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('wb_rggblevelsauto', 'WB RGGB Levels Auto', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('colortempauto', 'Color Temp Auto', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('wb_rggblevelsdaylight', 'WB RGGB Levels Daylight', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('colortempdaylight', 'Color Temp Daylight', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('wb_rggblevelsshade', 'WB RGGB Levels Shade', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('colortempshade', 'Color Temp Shade', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('wb_rggblevelscloudy', 'WB RGGB Levels Cloudy', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('colortempcloudy', 'Color Temp Cloudy', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('wb_rggblevelstungsten', 'WB RGGB Levels Tungsten', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('colortemptungsten', 'Color Temp Tungsten', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('wb_rggblevelsfluorescent', 'WB RGGB Levels Fluorescent', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('colortempfluorescent', 'Color Temp Fluorescent', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('wb_rggblevelsflash', 'WB RGGB Levels Flash', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('colortempflash', 'Color Temp Flash', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('wb_rggblevelscustom1', 'WB RGGB Levels Custom 1', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('colortempcustom1', 'Color Temp Custom 1', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('wb_rggblevelscustom2', 'WB RGGB Levels Custom 2', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('colortempcustom2', 'Color Temp Custom 2', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('colorhue', 'Color Hue', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('usercomment', 'User Comment', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('flashpixversion', 'Flashpix Version', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('colorspace', 'Color Space', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('exifimagewidth', 'Exif Image Width', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('exifimagelength', 'Exif Image Length', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('interopindex', 'Interoperability Index', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('interopversion', 'Interoperability Version', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('focalplanexresolution', 'Focal Plane X Resolution', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('focalplaneyresolution', 'Focal Plane Y Resolution', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('focalplaneresolutionunit', 'Focal Plane Resolution Unit', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('customrendered', 'Custom Rendered', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('exposuremode', 'Exposure Mode', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('scenecapturetype', 'Scene Capture Type', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('compression', 'Compression', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('thumbnailoffset', 'Thumbnail Offset', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('thumbnaillength', 'Thumbnail Length', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('profilecmmtype', 'Profile CMM Type', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('profileversion', 'Profile Version', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('profileclass', 'Profile Class', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('colorspacedata', 'Color Space Data', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('profileconnectionspace', 'Profile Connection Space', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('profiledatetime', 'Profile Date Time', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('profilefilesignature', 'Profile File Signature', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('primaryplatform', 'Primary Platform', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('cmmflags', 'CMM Flags', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('devicemanufacturer', 'Device Manufacturer', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('devicemodel', 'Device Model', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('deviceattributes', 'Device Attributes', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('renderingintent', 'Rendering Intent', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('connectionspaceilluminant', 'Connection Space Illuminant', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('profilecreator', 'Profile Creator', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('profileid', 'Profile ID', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('redmatrixcolumn', 'Red Matrix Column', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('greenmatrixcolumn', 'Green Matrix Column', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('bluematrixcolumn', 'Blue Matrix Column', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('mediawhitepoint', 'Media White Point', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('chromaticadaptation', 'Chromatic Adaptation', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('redtrc', 'Red Tone Reproduction Curve', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('greentrc', 'Green Tone Reproduction Curve', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('bluetrc', 'Blue Tone Reproduction Curve', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('profiledescription', 'Profile Description', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('profilecopyright', 'Profile Copyright', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('profiledescriptionml', 'Profile Description ML', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('imagewidth', 'Image Width', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('imageheight', 'Image Height', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('aperture', 'Aperture', true, true, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('drivemode', 'Drive Mode', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('flashon', 'Flash', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('imagesize', 'Image Size', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('lens', 'Lens', true, true, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('scalefactor35efl', 'Scale Factor To 35mm Equivalent', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('shootingmode', 'Shooting Mode', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('shutterspeed', 'Shutter Speed', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('thumbnailimage', 'Thumbnail Image', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('wb_rggblevels', 'WB RGGB Levels', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('bluebalance', 'Blue Balance', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('circleofconfusion', 'Circle Of Confusion', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('focallength35efl', 'Focal Length', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('hyperfocaldistance', 'Hyperfocal Distance', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('lens35efl', 'Lens', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('lightvalue', 'Light Value', false, false, null);
insert into PinholeMetaData (shortname, title, show, machine_tag, instance) values ('redbalance', 'Red Balance', false, false, null);
